# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'carborn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for carborn
  pod 'AFNetworking', '~> 3.0'
  pod 'SDWebImage', '~> 3.8.2'

  target 'carbornTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'carbornUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
